## Lista 1

In [34]:
import numpy as np
import numpy.linalg as LA
import sympy

np.set_printoptions(precision=3)

### Questão 15b

In [35]:
R = np.array([[1, 0.8, 0.64, 0.512], [0.8, 1, 0.8, 0.64], [0.64, 0.8, 1, 0.8], [0.512, 0.64, 0.8, 1]])
invR = LA.inv(R)
print(np.round(invR, 2))

[[ 2.78 -2.22  0.   -0.  ]
 [-2.22  4.56 -2.22  0.  ]
 [ 0.   -2.22  4.56 -2.22]
 [-0.    0.   -2.22  2.78]]


In [36]:
p = 1/4 * np.array([[0.4096, 0.512, 0.64, 0.8]]).T

In [37]:
wo = invR.dot(p)
print(np.round(wo,3))

[[0. ]
 [0. ]
 [0. ]
 [0.2]]


### Questão 16

Considerando os resultados da 15b

In [39]:
autovalores = LA.eigvals(R)
autovalores

array([3.103, 0.559, 0.209, 0.129])

In [41]:
mi_max = 1/3.103
mi_max

0.32226877215597804

In [44]:
def gw(w):
    return -2 * p + 2 * R * w

Para cada iteração

In [47]:
w0 = np.matrix('0;0;0;0')
mu = 0.1

gw0 = gw(w0)
w1 = w0 - mu * gw0
w1

matrix([[0.02 ],
        [0.026],
        [0.032],
        [0.04 ]])

In [48]:
gw1 = gw(w1)
w2 = w1 - mu * gw1
w2

matrix([[0.025],
        [0.033],
        [0.044],
        [0.062]])

In [49]:
gw2 = gw(w2)
w3 = w2 - mu * gw2
w3

matrix([[0.023],
        [0.033],
        [0.049],
        [0.075]])

In [51]:
gw3 = gw(w3)
w4 = w3 - mu * gw3
w4

matrix([[0.02 ],
        [0.031],
        [0.051],
        [0.086]])

In [52]:
gw4 = gw(w4)
w5 = w4 - mu * gw4
w5

matrix([[0.016],
        [0.028],
        [0.052],
        [0.095]])

In [53]:
gw5 = gw(w5)
w6 = w5 - mu * gw5
w6

matrix([[0.012],
        [0.025],
        [0.052],
        [0.102]])

In [54]:
gw6 = gw(w6)
w7 = w6 - mu * gw6
w7

matrix([[0.009],
        [0.022],
        [0.052],
        [0.109]])

In [56]:
gw7 = gw(w7)
w8 = w7 - mu * gw7
w8

matrix([[0.007],
        [0.02 ],
        [0.051],
        [0.115]])

In [58]:
gw8 = gw(w8)
w9 = w7 - mu * gw8
w9

matrix([[0.007],
        [0.02 ],
        [0.051],
        [0.115]])

In [59]:
gw9 = gw(w9)
w10 = w9 - mu * gw9
w10

matrix([[0.005],
        [0.017],
        [0.05 ],
        [0.12 ]])

### Questão 17

Considerando os resultados de 15b

In [60]:
w1 = w0 - mu * invR * gw(w0)
w1

matrix([[ 1.388e-17],
        [-1.388e-17],
        [ 0.000e+00],
        [ 4.000e-02]])

In [61]:
w2 = w1 - mu * invR * gw(w1)
w2

matrix([[ 1.388e-17],
        [-2.776e-17],
        [ 0.000e+00],
        [ 7.200e-02]])

In [62]:
w3 = w2 - mu * invR * gw(w2)
w3

matrix([[ 2.082e-17],
        [-1.388e-17],
        [ 0.000e+00],
        [ 9.760e-02]])

In [63]:
w4 = w3 - mu * invR * gw(w3)
w4

matrix([[ 2.082e-17],
        [-1.388e-17],
        [ 0.000e+00],
        [ 1.181e-01]])

In [64]:
w5 = w4 - mu * invR * gw(w4)
w5

matrix([[ 2.082e-17],
        [-2.082e-17],
        [-6.939e-18],
        [ 1.345e-01]])

In [65]:
w6 = w5 - mu * invR * gw(w5)
w6

matrix([[ 2.776e-17],
        [-2.776e-17],
        [ 6.939e-18],
        [ 1.476e-01]])

In [66]:
w7 = w6 - mu * invR * gw(w6)
w7

matrix([[ 2.949e-17],
        [-3.469e-17],
        [ 1.388e-17],
        [ 1.581e-01]])

In [67]:
w8 = w7 - mu * invR * gw(w7)
w8

matrix([[ 1.908e-17],
        [-1.735e-17],
        [-6.939e-18],
        [ 1.664e-01]])

In [68]:
w9 = w8 - mu * invR * gw(w8)
w9

matrix([[ 2.082e-17],
        [-1.735e-17],
        [-1.041e-17],
        [ 1.732e-01]])

In [69]:
w10 = w9 - mu * invR * gw(w9)
w10

matrix([[ 2.689e-17],
        [-4.163e-17],
        [ 1.041e-17],
        [ 1.785e-01]])